name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        work-dir: [server]
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v1.0.0
    - name: Installing npm packages
      run: npm install
      working-directory: ${{ matrix.work-dir }}
    - name: Moving src/config/prod.js to src/config/dev.js
      run: mv src/config/prod.js src/config/dev.js
      working-directory: ${{ matrix.work-dir }}
    - name: Running `npm test`
      run: npm test
      working-directory: ${{ matrix.work-dir }}
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/dev # Access mongoDB Docker container
        
